version: 2

jobs:
  build:
    working_directory: ~/zengin-js
    docker:
      - image: circleci/ruby:2.5-node
    steps:
      - checkout
      - run:
          name: Dependency
          command: npm install
      - run:
          name: Build
          command: npm run build
      - run:
          name: Deployment
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then npm run ci; fi
